### PR TITLE
parameter to set commit limit as requested

### PR DESCRIPTION
**Pull request by titabo2k**
occasionally we need the option to commit smaller chunks

### CODE REVIEW

**Comment by miku** [comment]
Thanks, just released this with [0.2.13](https://pypi.org/project/gluish/).

**Comment by zazi** [comment]
I would recommend to keep the default at 1.000.000 - as it is the default value for 'commit' in solrbulk, or?

**Comment by miku** [comment]
> Hard commits truncate the current segment and open a new segment in your index. 

This is quite expensive and we mostly use solrbulk in a case, where we do not need visibility of documents right away - that's why the relatively high 1M as default. 

Apart from that, the current solrconfig has [autoCommit enabled](https://github.com/finc/index/blob/aedeeb017b348e42e7940f6d6d9d461ad0547d04/solrconfig.xml#L131-L134), which

> controls how often pending updates will be automatically pushed to the index

As I write this, I fear, the current autoCommit ([docs](https://lucene.apache.org/solr/guide/6_6/updatehandlers-in-solrconfig.html#UpdateHandlersinSolrConfig-autoCommit)) of 15s is suboptimal for the article index, we should probably increase this setting and see whether we get better performance (data point: currently we index consistently around 5K docs/s on a single node).

**Comment by zazi** [comment]
anyway, how to deal with

> I would recommend to keep the default at 1.000.000 - as it is the default value for 'commit' in solrbulk, or?

?

currently, the default value in the luigi task in gluish is 1000 (which is probably not really recommend re. your argumentation)

**Comment by miku** [comment]
If I understand correctly: It is always possible to overwrite any parameter, either on the command line:

    $ python mytasks.py MyTaskName --commitlimit 1000000

Here `MyTaskName` would need to pass on the parameter (which can be a bit tedious and leads to boilerplate).

Luigi offers a way to [overwrite parameters of other tasks](https://luigi.readthedocs.io/en/stable/parameters.html#setting-parameter-value-for-other-classes) with some slightly different syntax, `--class-parameter`, e.g.:

    $ python mytasks.py MyTaskName --FillSolrIndex-commitlimit 1000000

In code, it is also possible to override the default parameters:

```python
...
def requires(self):
    return FillSolrIndex(commitlimit=1000000)
...
```

Apart from that, I would suggest to increase the default limit, since solrbulk will issue an explicit commit to SOLR at the end of the indexing anyway and bigger datasets will presumably a bit faster with less frequent commits.

**Comment by zazi** [comment]
> Apart from that, I would suggest to increase the default limit, since solrbulk will issue an explicit commit to SOLR at the end of the indexing anyway and bigger datasets will presumably a bit faster with less frequent commits.

yepp, that's what I meant, i.e., this was the intention of my initial comment ;)

**Pull request merged**
